<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/styles.css" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

		<?php echo $this->headScript(); ?>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
	</head>
	<body>

        <div class="container">
            <div class="row">

                <!-- left column -->
                <div class="col-sm-2">
                    <h3>Menu</h3>
                    <ul class="nav nav-pills nav-stacked">
                        <li role="presentation" class="active"><a href="/">All Questions</a></li>
                        <li role="presentation"><a href="/palindrome">Question 1</a></li>
                        <li role="presentation"><a href="/interface">Question 2</a></li>
                        <li role="presentation"><a href="/missingletter">Question 3</a></li>
                        <li role="presentation"><a href="/fizzbuzz">Question 4</a></li>
                        <li role="presentation"><a href="/shortestword">Question 5</a></li>
                        <li role="presentation"><a href="/uniquenumber">Question 6</a></li>
                    </ul>
                </div>

                <!-- main column -->
                <div class="col-sm-9">

<?php echo $this->layout()->content; ?>
<?php echo $this->inlineScript(); ?>

                </div><!-- /col -->

            </div><!-- /row -->
        </div><!-- /container -->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="js/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="js/bootstrap.min.js"></script>
	</body>
</html>